const mongoose = require('mongoose');
require('dotenv').config();

const schemeSchema = new mongoose.Schema({
  title: String,
  description: String,
  category: String,
  tags: [String],
  deadline: String,
  benefits: [String],
  criteria: [String],
  steps: [String],
  link: String,
  eligibilityRules: {
    minAge: Number,
    maxAge: Number,
    gender: [String],
    states: [String],
    occupations: [String],
    incomeRange: [String],
    categories: [String],
  },
});
const Scheme = mongoose.model('Scheme', schemeSchema);

const schemes = [
  {
    title: 'PM Kisan Samman Nidhi (PM-KISAN)',
    description: 'Financial support of Rs.6,000 per year to all landholding farmer families across India, paid in three equal installments directly to bank accounts.',
    category: 'agriculture',
    tags: ['Agriculture', 'Financial Assistance', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Rs.6,000 per year in three installments of Rs.2,000 each', 'Direct Benefit Transfer (DBT) to bank account', 'Reduces dependence on moneylenders', 'Covers all small and marginal farmers'],
    criteria: ['Must be a landholding farmer family', 'Must possess a valid Aadhaar card', 'Active bank account linked to Aadhaar required', 'Not a government employee or income tax payer', 'Not a retired pensioner receiving Rs.10,000+ per month'],
    steps: ['Visit the official PM-KISAN portal at pmkisan.gov.in', 'Click on "New Farmer Registration"', 'Enter Aadhaar number and complete the captcha', 'Fill in personal, bank account, and land details', 'Submit the form and save your reference number'],
    link: 'https://pmkisan.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    description: 'Crop insurance scheme providing financial support to farmers suffering crop loss/damage due to unforeseen events like natural calamities, pests, and diseases.',
    category: 'agriculture',
    tags: ['Agriculture', 'Insurance', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Insurance coverage for crop loss due to natural calamities', 'Very low premium: 2% for Kharif, 1.5% for Rabi crops', 'Full insurance amount paid for complete crop failure', 'Post-harvest losses also covered for up to 14 days'],
    criteria: ['Must be a farmer (loanee or non-loanee)', 'Must be growing notified crops in notified areas', 'Valid land records or tenancy documents required', 'Aadhaar number mandatory for enrollment'],
    steps: ['Visit the nearest bank or Common Service Centre or go to pmfby.gov.in', 'Fill in the crop insurance application form', 'Submit land records, Aadhaar, and bank details', 'Pay your share of the premium', 'Receive acknowledgment and policy certificate'],
    link: 'https://pmfby.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Kisan Credit Card (KCC)',
    description: 'Provides farmers with affordable and timely credit for agricultural needs, post-harvest expenses, and allied activities through a simple credit card system.',
    category: 'agriculture',
    tags: ['Agriculture', 'Credit', 'Financial Assistance', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Credit limit up to Rs.3 lakh at subsidized interest rate of 4% p.a.', 'Flexible repayment linked to harvesting season', 'Personal accident insurance of Rs.50,000 included', 'No collateral required for loans up to Rs.1.6 lakh'],
    criteria: ['Must be a farmer, sharecropper, or oral lessee', 'Should be engaged in agriculture or allied activities', 'Good credit history with lending institution'],
    steps: ['Visit your nearest bank branch', 'Request the KCC application form', 'Submit land records, identity proof, and address proof', 'Bank evaluates and sanctions the credit limit', 'Receive KCC card and begin using credit for farming needs'],
    link: 'https://pmkisan.gov.in/KCC.aspx',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Post Matric Scholarship for SC Students',
    description: 'Central government scholarship for Scheduled Caste students studying at post-matriculation level to cover tuition, maintenance, and other educational expenses.',
    category: 'education',
    tags: ['Education', 'Scholarship', 'SC/ST', 'Central'],
    deadline: '2026-10-31',
    benefits: ['Maintenance allowance for living expenses', 'Reimbursement of compulsory non-refundable fees', 'Study tour charges covered', 'Thesis typing and printing charges for research scholars'],
    criteria: ['Must belong to Scheduled Caste (SC) category', 'Family income must not exceed Rs.2.5 lakh per annum', 'Must be enrolled in a post-matriculation course', 'Must be studying in a government-recognized institution', 'Should not be receiving any other scholarship'],
    steps: ['Register on the National Scholarship Portal at scholarships.gov.in', 'Login and select Post Matric Scholarship for SC', 'Fill in personal, academic, and bank details', 'Upload caste certificate, income certificate, and marksheets', 'Submit application before the deadline and note down application ID'],
    link: 'https://scholarships.gov.in/',
    eligibilityRules: { minAge: 15, maxAge: 35, gender: ['Any'], states: ['All'], occupations: ['Student'], incomeRange: ['below_1L', '1L_to_2.5L'], categories: ['SC'] },
  },
  {
    title: 'Post Matric Scholarship for ST Students',
    description: 'Central government scholarship for Scheduled Tribe students pursuing post-matriculation education to reduce dropout rates and promote higher education.',
    category: 'education',
    tags: ['Education', 'Scholarship', 'SC/ST', 'Central'],
    deadline: '2026-10-31',
    benefits: ['Full tuition fee reimbursement for government institutions', 'Monthly maintenance allowance based on course level', 'Book grant and stationery allowance', 'Hostel allowance for outstation students'],
    criteria: ['Must belong to Scheduled Tribe (ST) category', 'Family income must not exceed Rs.2.5 lakh per annum', 'Must be enrolled in a post-matriculation course', 'Must be a regular student at recognized institution'],
    steps: ['Visit scholarships.gov.in and complete registration', 'Select Post Matric Scholarship for ST', 'Fill application with academic and family income details', 'Upload tribe certificate, marksheets, and income proof', 'Submit and track application status on the portal'],
    link: 'https://scholarships.gov.in/',
    eligibilityRules: { minAge: 15, maxAge: 35, gender: ['Any'], states: ['All'], occupations: ['Student'], incomeRange: ['below_1L', '1L_to_2.5L'], categories: ['ST'] },
  },
  {
    title: 'National Means-cum-Merit Scholarship (NMMS)',
    description: 'Scholarship for economically weaker section students to prevent dropout at Class VIII level and encourage them to continue education up to Class XII.',
    category: 'education',
    tags: ['Education', 'Scholarship', 'Merit', 'Central'],
    deadline: '2026-09-30',
    benefits: ['Rs.12,000 per year scholarship', 'Scholarship continues from Class IX to XII', 'Direct transfer to student bank account', 'Covers approximately 1 lakh students annually'],
    criteria: ['Must be studying in Class VIII in a government school', 'Family income must not exceed Rs.3.5 lakh per annum', 'Must have scored at least 55% in Class VII', 'Must clear the NMMS state-level selection test'],
    steps: ['Check NMMS exam notification from your State Education Department', 'Fill the application form available at school or state portal', 'Appear for the State Level NMMS Examination', 'If selected, register on scholarships.gov.in', 'Submit verified documents and bank account details'],
    link: 'https://scholarships.gov.in/',
    eligibilityRules: { minAge: 13, maxAge: 18, gender: ['Any'], states: ['All'], occupations: ['Student'], incomeRange: ['below_1L', '1L_to_2.5L', '2.5L_to_5L'], categories: ['Any'] },
  },
  {
    title: 'Prime Minister Scholarship Scheme (PMSS)',
    description: 'Scholarship for wards of ex-servicemen and Coast Guard personnel who were killed or disabled in action, to encourage professional education.',
    category: 'education',
    tags: ['Education', 'Scholarship', 'Defence', 'Central'],
    deadline: '2026-11-30',
    benefits: ['Rs.3,000 per month for boys and Rs.3,500 per month for girls', 'Available for 1st to 4th year of professional degree courses', '5,500 scholarships awarded annually'],
    criteria: ['Must be ward or widow of ex-serviceman or Coast Guard', 'Must be pursuing first professional degree (MBBS, B.Tech, etc.)', 'Minimum 60% marks in qualifying examination', 'Age between 18-25 years at time of admission'],
    steps: ['Visit the Kendriya Sainik Board portal at ksb.gov.in', 'Register and fill the online PMSS application form', 'Upload relevant documents including ex-serviceman certificate', 'Submit before the deadline', 'Track selection results on the portal'],
    link: 'https://ksb.gov.in/prime-minister-scholarship-scheme.htm',
    eligibilityRules: { minAge: 18, maxAge: 25, gender: ['Any'], states: ['All'], occupations: ['Student'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Beti Bachao Beti Padhao (BBBP)',
    description: 'National campaign to address declining child sex ratio and promote welfare and education of the girl child across all districts of India.',
    category: 'women',
    tags: ['Women', 'Education', 'Girl Child', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Sukanya Samriddhi Account with 8.2% interest p.a.', 'Free education for girls in government schools', 'Conditional cash transfers in participating states', 'Awareness campaigns and community mobilization'],
    criteria: ['Family with a girl child', 'Girl must be under 10 years for Sukanya Samriddhi Account', 'No income restriction for general awareness programs', 'Must be an Indian citizen'],
    steps: ['Open a Sukanya Samriddhi Account at a post office or authorized bank', 'Provide the girl child birth certificate', 'Submit identity and address proof of parent or guardian', 'Deposit a minimum of Rs.250 per year into the account', 'Account matures when the girl turns 21 or at marriage after 18'],
    link: 'https://wcd.nic.in/bbbp-schemes',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Female'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
    description: 'Maternity benefit program providing Rs.5,000 in cash incentives to pregnant women and lactating mothers for their first living child to compensate for wage loss.',
    category: 'women',
    tags: ['Women', 'Maternity', 'Health', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Rs.5,000 cash incentive in three installments', 'First installment of Rs.1,000 on early registration of pregnancy', 'Second installment of Rs.2,000 after at least one antenatal check-up', 'Third installment of Rs.2,000 after child birth registration and first vaccination'],
    criteria: ['Pregnant women aged 19 years and above', 'Applicable for first living child only', 'Must not be a regular employee of Central or State government', 'Registration at Anganwadi Centre required'],
    steps: ['Visit your nearest Anganwadi Centre or health facility', 'Register your pregnancy and fill Form 1A', 'Receive first installment after registration', 'Submit Form 1B after antenatal check-up for second installment', 'Submit Form 1C after child birth registration for third installment'],
    link: 'https://wcd.nic.in/schemes/pradhan-mantri-matru-vandana-yojana',
    eligibilityRules: { minAge: 19, maxAge: 45, gender: ['Female'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Mahila Samridhi Yojana',
    description: 'Microfinance scheme providing collateral-free loans to women entrepreneurs from SC/ST communities for starting or expanding small businesses.',
    category: 'women',
    tags: ['Women', 'SC/ST', 'Employment', 'Loan', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Loans up to Rs.1.4 lakh at subsidized interest rates', 'No collateral or guarantor required', 'Loan repayable in weekly or monthly installments', 'Training and capacity building support provided'],
    criteria: ['Must be a woman entrepreneur from SC or ST community', 'Age between 18 and 55 years', 'Must be involved in income-generating activities', 'Family income should not exceed Rs.3 lakh per annum'],
    steps: ['Contact the nearest NSFDC state office', 'Fill the application form with business plan details', 'Submit caste certificate, income proof, and address proof', 'Attend loan interview and project evaluation', 'Receive loan disbursement after approval'],
    link: 'https://nsfdc.nic.in/',
    eligibilityRules: { minAge: 18, maxAge: 55, gender: ['Female'], states: ['All'], occupations: ['Self-Employed', 'Unemployed', 'Homemaker'], incomeRange: ['below_1L', '1L_to_2.5L', '2.5L_to_5L'], categories: ['SC', 'ST'] },
  },
  {
    title: 'Pradhan Mantri Awas Yojana Gramin (PMAY-G)',
    description: 'Provides pucca (permanent) houses with basic amenities to all homeless and those living in kutcha or dilapidated houses in rural areas.',
    category: 'housing',
    tags: ['Housing', 'Rural', 'BPL', 'Central'],
    deadline: '2027-03-31',
    benefits: ['Rs.1.2 lakh assistance in plain areas (Rs.1.3 lakh in hilly areas)', 'Additional Rs.12,000 for construction of toilet under Swachh Bharat Mission', 'MGNREGS support for 90 days of unskilled labor', 'Free LPG connection under Ujjwala Yojana for beneficiaries'],
    criteria: ['Must be from rural area and listed in SECC 2011 data', 'Must be homeless or living in a kutcha or deteriorating house', 'Priority to SCs, STs, minorities, and families with disabled members', 'Should not own any pucca house in India'],
    steps: ['Your name should appear in the SECC 2011 beneficiary list', 'Contact your Gram Panchayat or Block Development Officer', 'Verify details through AwaasSoft MIS system', 'Receive first installment after geo-tagged photo submitted', 'Receive subsequent installments at each construction stage'],
    link: 'https://pmayg.nic.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer', 'Unemployed', 'Homemaker'], incomeRange: ['below_1L', '1L_to_2.5L'], categories: ['Any'] },
  },
  {
    title: 'Pradhan Mantri Awas Yojana Urban (PMAY-U)',
    description: 'Credit-linked subsidy scheme for urban poor to construct or purchase a pucca house, targeting EWS, LIG, and MIG categories.',
    category: 'housing',
    tags: ['Housing', 'Urban', 'Subsidy', 'Central'],
    deadline: '2027-12-31',
    benefits: ['Interest subsidy of up to 6.5% on home loans for EWS/LIG', 'Subsidy of 4% for MIG-I and 3% for MIG-II', 'One-time subsidy credited directly to loan account', 'Reduces EMI significantly for affordable housing'],
    criteria: ['Must be from EWS (income up to Rs.3L), LIG (Rs.3L-Rs.6L), or MIG (Rs.6L-Rs.18L)', 'Beneficiary family should not own a pucca house anywhere in India', 'Must purchase or construct house in urban area', 'Aadhaar mandatory for all adult members of beneficiary family'],
    steps: ['Visit the PMAY Urban portal at pmaymis.gov.in', 'Check eligibility under the appropriate category', 'Apply through your bank or housing finance company for home loan', 'Submit PMAY application along with loan application', 'Subsidy credited to loan account after verification'],
    link: 'https://pmaymis.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Salaried', 'Self-Employed', 'Unemployed'], incomeRange: ['below_1L', '1L_to_2.5L', '2.5L_to_5L', '5L_to_8L'], categories: ['Any'] },
  },
  {
    title: 'Ayushman Bharat PM Jan Arogya Yojana (PM-JAY)',
    description: 'World largest health insurance scheme providing Rs.5 lakh coverage per family per year for secondary and tertiary hospitalization to the bottom 40% of population.',
    category: 'health',
    tags: ['Health', 'Insurance', 'BPL', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Rs.5 lakh health cover per family per year', 'Covers 1,929+ medical procedures including surgery and cancer treatment', 'Cashless treatment at 25,000+ empanelled hospitals', 'Pre and post-hospitalization expenses covered', 'No cap on family size or age'],
    criteria: ['Must be listed in SECC 2011 database for rural deprivation criteria', 'Urban workers from 11 occupational categories are eligible', 'No restriction on age or pre-existing conditions', 'No premium required from beneficiary families'],
    steps: ['Check eligibility at pmjay.gov.in or call 14555', 'Visit a government hospital or empanelled private hospital', 'Show Aadhaar or ration card for identity verification', 'Hospital generates e-card from PMJAY portal', 'Receive cashless treatment without any payment'],
    link: 'https://pmjay.gov.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer', 'Unemployed', 'Homemaker', 'Self-Employed'], incomeRange: ['below_1L', '1L_to_2.5L', '2.5L_to_5L'], categories: ['Any'] },
  },
  {
    title: 'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
    description: 'Accidental death and disability insurance scheme offering Rs.2 lakh coverage at an annual premium of just Rs.20, targeting the uninsured population.',
    category: 'health',
    tags: ['Health', 'Insurance', 'Accident', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Rs.2 lakh on accidental death or total permanent disability', 'Rs.1 lakh for partial permanent disability', 'Annual premium of only Rs.20 auto-debited from bank account', 'Coverage period: June 1 to May 31 every year'],
    criteria: ['Age between 18 and 70 years', 'Must have a savings bank account', 'Must give consent for auto-debit of premium', 'Aadhaar should be linked to bank account'],
    steps: ['Visit your bank branch or internet banking portal', 'Opt for Pradhan Mantri Suraksha Bima Yojana', 'Give auto-debit consent for Rs.20 annual premium', 'Receive confirmation of enrollment', 'In case of accident, contact your bank to initiate claim'],
    link: 'https://www.jansuraksha.gov.in/Forms-PMSBY.aspx',
    eligibilityRules: { minAge: 18, maxAge: 70, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
    description: 'Life insurance scheme offering Rs.2 lakh term coverage at a premium of Rs.436 per year for the age group 18-50 years.',
    category: 'health',
    tags: ['Health', 'Insurance', 'Life Insurance', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Rs.2 lakh term life insurance coverage', 'Annual premium of only Rs.436 auto-debited from bank', 'Coverage for death due to any cause', 'Easy renewal every year'],
    criteria: ['Age between 18 and 50 years', 'Must have a savings bank account', 'Must give auto-debit consent for premium payment'],
    steps: ['Visit your bank or go to bank internet banking', 'Opt for PMJJBY scheme', 'Fill the enrollment form and give auto-debit consent', 'Annual premium of Rs.436 will be auto-debited from account', 'Coverage starts and nominee receives Rs.2 lakh on policyholder death'],
    link: 'https://www.jansuraksha.gov.in/Forms-PMJJBY.aspx',
    eligibilityRules: { minAge: 18, maxAge: 50, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'PM Employment Generation Programme (PMEGP)',
    description: 'Credit-linked subsidy program to generate employment by establishing micro-enterprises in non-farm sector for unemployed youth and traditional artisans.',
    category: 'employment',
    tags: ['Employment', 'Self-Employment', 'Loan', 'Subsidy', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Subsidy of 15-35% of project cost', 'Higher subsidy for SC/ST, women, ex-servicemen, and NER applicants', 'Projects up to Rs.50 lakh for manufacturing and Rs.20 lakh for service sectors', 'Banks provide remaining loan at normal interest rates'],
    criteria: ['Age above 18 years', 'Minimum 8th pass for projects above Rs.10 lakh', 'Must not have any existing loan from other government scheme', 'New enterprises only'],
    steps: ['Register on the PMEGP e-portal at kviconline.gov.in/pmegpeportal', 'Fill in personal and project details in the online application', 'Submit application and download the filled form', 'Submit hard copy to nearest KVIC/KVIB/DIC office', 'Attend interview and EDP training if shortlisted', 'Receive loan and subsidy after bank sanction'],
    link: 'https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Unemployed', 'Self-Employed'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Startup India Scheme',
    description: 'Government initiative to build a strong ecosystem for nurturing innovation and startups in India, providing tax benefits, funding support, and regulatory ease.',
    category: 'employment',
    tags: ['Employment', 'Startup', 'Innovation', 'Tax Benefit', 'Central'],
    deadline: 'Ongoing',
    benefits: ['3-year income tax exemption (80IAC)', 'Exemption from capital gains tax', 'Fast-track patent application with 80% fee rebate', 'Access to Rs.10,000 crore Fund of Funds for Startups', 'Self-certification under 6 labour and 3 environment laws'],
    criteria: ['Company incorporated in India as Private Ltd, LLP, or Partnership', 'Company must be less than 10 years old', 'Annual turnover should not exceed Rs.100 crore', 'Must be working on innovation or development of products or services'],
    steps: ['Register company with MCA', 'Visit startupindia.gov.in and create an account', 'Fill Startup recognition application with company details', 'Upload incorporation certificate and description of innovative nature', 'Receive Startup India recognition certificate within 2 working days'],
    link: 'https://www.startupindia.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Self-Employed'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'PM SVANidhi (Street Vendor Micro-Credit)',
    description: 'Micro-credit facility for street vendors to resume their livelihoods affected by COVID-19 and graduate to higher credit limits with good repayment.',
    category: 'employment',
    tags: ['Employment', 'Micro-Credit', 'Street Vendors', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Collateral-free working capital loan of Rs.10,000 initially', 'Subsequent loans of Rs.20,000 and Rs.50,000 on timely repayment', '7% interest subsidy per annum', 'Digital transactions incentivized with cashback up to Rs.1,200/year'],
    criteria: ['Must be a street vendor who was vending before March 24, 2020', 'Must have Certificate of Vending or Letter of Recommendation from ULB', 'Must have Aadhaar linked to mobile number', 'Must be operating in urban area'],
    steps: ['Visit pmsvanidhi.mohua.gov.in or nearest Common Service Centre', 'Fill online application with personal and vendor details', 'Submit CoV or LoR from local Urban Local Body', 'Bank verifies details and sanctions the loan', 'Repay on time to become eligible for higher loan amount'],
    link: 'https://pmsvanidhi.mohua.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Self-Employed', 'Unemployed'], incomeRange: ['below_1L', '1L_to_2.5L'], categories: ['Any'] },
  },
  {
    title: 'Atal Pension Yojana (APY)',
    description: 'Government-backed pension scheme for unorganized sector workers guaranteeing a fixed pension of Rs.1,000 to Rs.5,000 per month after age 60.',
    category: 'employment',
    tags: ['Employment', 'Pension', 'Retirement', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Guaranteed pension of Rs.1,000 to Rs.5,000 per month after age 60', 'Same pension continues for spouse after subscriber death', 'Return of pension wealth to nominee after both subscriber and spouse die', 'Government co-contributes 50% or Rs.1,000/year for eligible subscribers'],
    criteria: ['Age between 18 and 40 years', 'Must have a savings bank account', 'Must not be an income tax payer to get government co-contribution', 'Must not be covered under any statutory social security scheme'],
    steps: ['Visit your bank branch or open account via net banking', 'Fill APY registration form with nominee and pension amount details', 'Auto-debit will be set up for monthly contribution', 'Contribution amount depends on age and chosen pension amount', 'Receive pension after turning 60 years'],
    link: 'https://npscra.nsdl.co.in/scheme-details.php',
    eligibilityRules: { minAge: 18, maxAge: 40, gender: ['Any'], states: ['All'], occupations: ['Farmer', 'Self-Employed', 'Homemaker', 'Unemployed'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'MGNREGA (Mahatma Gandhi National Rural Employment Guarantee)',
    description: 'Legal guarantee of 100 days of paid employment per year to adult members of rural households willing to do unskilled manual work at statutory minimum wages.',
    category: 'employment',
    tags: ['Employment', 'Rural', 'Wage Employment', 'Central'],
    deadline: 'Ongoing',
    benefits: ['100 days of guaranteed wage employment per household per year', 'Wage paid at state MGNREGA rate (Rs.200-Rs.300/day)', 'Employment provided within 5 km of residence or extra wages paid', 'If work not provided within 15 days, unemployment allowance given'],
    criteria: ['Must be an adult member (18+ years) of a rural household', 'Must be willing to do unskilled manual work', 'Must possess a Job Card issued by Gram Panchayat', 'Priority to SC/ST, women, and disabled persons'],
    steps: ['Submit application to Gram Panchayat with photos and identity proof', 'Receive Job Card from Gram Panchayat within 15 days', 'Submit demand for work in writing to Gram Panchayat', 'Work will be allocated within 15 days of demand', 'Wages will be paid directly to bank account within 15 days of work'],
    link: 'https://nrega.nic.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer', 'Unemployed', 'Homemaker'], incomeRange: ['below_1L', '1L_to_2.5L'], categories: ['Any'] },
  },
  {
    title: 'Ladli Behna Yojana (Madhya Pradesh)',
    description: 'MP state scheme providing Rs.1,250 per month to all eligible women between 21-60 years to enhance their financial independence and health.',
    category: 'women',
    tags: ['Women', 'Financial Assistance', 'State Scheme'],
    deadline: 'Ongoing',
    benefits: ['Rs.1,250 per month direct bank transfer (Rs.15,000/year)', 'Covers all eligible women aged 21-60 in MP', 'Additional benefits linked to other state government schemes'],
    criteria: ['Must be a woman aged 21-60 years', 'Must be a domicile of Madhya Pradesh', 'Family income must not exceed Rs.2.5 lakh per annum', 'Must not be an income tax payer', 'Should not hold government job'],
    steps: ['Visit nearest Anganwadi Centre or MP government camp', 'Fill Ladli Behna Yojana application form', 'Provide Aadhaar, Samagra ID, and bank account details', 'eKYC verification through biometric or OTP', 'Approved applications receive monthly transfer by 10th of each month'],
    link: 'https://cmladlibahna.mp.gov.in/',
    eligibilityRules: { minAge: 21, maxAge: 60, gender: ['Female'], states: ['Madhya Pradesh'], occupations: ['Any'], incomeRange: ['below_1L', '1L_to_2.5L'], categories: ['Any'] },
  },
  {
    title: 'Mukhyamantri Kanya Utthan Yojana (Bihar)',
    description: 'Bihar state scheme providing financial assistance to girl children at various stages of education from birth to graduation to reduce female dropout rates.',
    category: 'women',
    tags: ['Women', 'Education', 'Girl Child', 'State Scheme'],
    deadline: 'Ongoing',
    benefits: ['Rs.5,000 at birth for girls born in families below poverty line', 'Rs.2,000 on completing Class XII', 'Rs.25,000 on completion of graduation (unmarried girls)', 'Sanitary napkin and uniform allowance provided'],
    criteria: ['Must be a girl child in Bihar', 'Family must be domicile of Bihar', 'For graduation benefit: must be unmarried at time of graduation', 'Benefits linked to Bihar government database'],
    steps: ['Visit edudbt.bih.nic.in for graduation incentive', 'Register with college details and upload mark sheet', 'Submit bank account and Aadhaar details', 'Verification done by college and district office', 'Amount transferred directly to student bank account'],
    link: 'https://edudbt.bih.nic.in/',
    eligibilityRules: { minAge: null, maxAge: 30, gender: ['Female'], states: ['Bihar'], occupations: ['Student'], incomeRange: ['below_1L', '1L_to_2.5L', '2.5L_to_5L'], categories: ['Any'] },
  },
  {
    title: 'Delhi Mukhyamantri Mahila Samman Yojana',
    description: 'Delhi government scheme providing Rs.1,000 per month financial assistance to all eligible women aged 18 years and above who are residents of Delhi.',
    category: 'women',
    tags: ['Women', 'Financial Assistance', 'State Scheme'],
    deadline: 'Ongoing',
    benefits: ['Rs.1,000 per month direct benefit transfer', 'Covers all eligible women in Delhi regardless of income', 'Simple enrollment process through Delhi government camps'],
    criteria: ['Must be a woman aged 18 years and above', 'Must be a voter of Delhi (listed in Delhi voter rolls)', 'Must not be a government employee', 'Must not be an income tax payer'],
    steps: ['Visit Delhi government mahila samman registration camp', 'Fill registration form with Aadhaar and voter ID', 'Submit bank account details for DBT', 'Verification by Delhi government officials', 'Monthly transfer of Rs.1,000 after approval'],
    link: 'https://delhi.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Female'], states: ['Delhi'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Rythu Bandhu Scheme (Telangana)',
    description: 'Telangana state investment support scheme providing Rs.10,000 per acre per season to farmers for purchase of inputs like seeds, fertilizers, pesticides, and labour.',
    category: 'agriculture',
    tags: ['Agriculture', 'Financial Assistance', 'State Scheme'],
    deadline: 'Ongoing',
    benefits: ['Rs.10,000 per acre per season (Rs.20,000 per year)', 'Covers both Kharif and Rabi seasons', 'Direct payment to farmer bank account before sowing season', 'No restrictions on how investment support is used'],
    criteria: ['Must be a farmer in Telangana', 'Must be a landowner (not tenant farmers)', 'Land must be agricultural land registered in Telangana', 'Must have Aadhaar linked bank account'],
    steps: ['Register at your nearest Agriculture Office in Telangana', 'Submit Pahani (land records) and Aadhaar card', 'Verify details through Telangana government database', 'Receive investment support before each cropping season'],
    link: 'https://rythubandhu.telangana.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['Telangana'], occupations: ['Farmer'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Amma Vodi Scheme (Andhra Pradesh)',
    description: 'Andhra Pradesh state scheme providing Rs.15,000 per year to mothers who send their children to school, to encourage school enrollment and reduce dropout.',
    category: 'education',
    tags: ['Education', 'Women', 'Financial Assistance', 'State Scheme'],
    deadline: 'Ongoing',
    benefits: ['Rs.15,000 per year per eligible mother', 'Funds can be used for child educational expenses', 'Covers government school students from Classes 1 to 12', 'Paid in two installments directly to mother bank account'],
    criteria: ['Must be a mother or guardian with children enrolled in government school', 'Must be a resident of Andhra Pradesh', 'Family should belong to BPL category or have annual income below Rs.2 lakh', 'Child must have 75%+ attendance'],
    steps: ['School enrollment of child in government school mandatory', 'Visit your child school for Amma Vodi registration', 'Submit Aadhaar, ration card, and bank account details', 'Annual verification of child school attendance', 'Funds transferred in January and June each year'],
    link: 'https://ammavodi.ap.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Female'], states: ['Andhra Pradesh'], occupations: ['Any'], incomeRange: ['below_1L', '1L_to_2.5L'], categories: ['Any'] },
  },
  {
    title: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)',
    description: 'Flagship skill development scheme enabling Indian youth to take up industry-relevant skill training to find better livelihoods, with free training and certification.',
    category: 'employment',
    tags: ['Employment', 'Skill Development', 'Youth', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Free skill training in 300+ job roles across 38 sectors', 'Government-recognized certification on completion', 'Monetary reward of Rs.500 to Rs.1,500 on certification', 'Placement assistance provided after training', 'Recognition of Prior Learning (RPL) for existing skills'],
    criteria: ['Indian citizen aged 15-45 years', 'Must be school or college dropout or unemployed', 'No mandatory educational qualification for most courses', 'Must have Aadhaar card'],
    steps: ['Visit the PMKVY website at pmkvyofficial.org', 'Find a training center near you using the locator tool', 'Enroll at the training center with Aadhaar and bank details', 'Complete the training program', 'Appear for sector skill council assessment', 'Receive certificate and placement support'],
    link: 'https://www.pmkvyofficial.org/',
    eligibilityRules: { minAge: 15, maxAge: 45, gender: ['Any'], states: ['All'], occupations: ['Unemployed', 'Student'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'PM Vishwakarma Yojana',
    description: 'Central scheme to support traditional artisans and craftspeople (Vishwakarmas) with skills, modern tools, digital empowerment, and collateral-free credit.',
    category: 'employment',
    tags: ['Employment', 'Artisans', 'Skill Development', 'Loan', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Recognition as Vishwakarma with PM Vishwakarma certificate', 'Skill training stipend of Rs.500/day during training', 'Toolkit incentive of Rs.15,000', 'Collateral-free loans: Rs.1 lakh (first tranche) and Rs.2 lakh (second)', 'Interest subsidy to cap rate at 5%'],
    criteria: ['Must practice one of 18 traditional trades (carpenter, blacksmith, goldsmith, potter, etc.)', 'Must be self-employed in unorganized sector', 'Age 18 years and above', 'Must not have availed loan under PMEGP/MUDRA in last 5 years'],
    steps: ['Visit pmvishwakarma.gov.in or nearest Common Service Centre', 'Register with Aadhaar biometric authentication', 'Fill trade details and family information', 'Attend skill training at designated institute', 'Apply for toolkit incentive and loan after training'],
    link: 'https://pmvishwakarma.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Self-Employed'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'PM MUDRA Yojana (PMMY)',
    description: 'Provides loans up to Rs.10 lakh to non-corporate, non-farm small and micro enterprises for income-generating activities in manufacturing, trading, and services.',
    category: 'employment',
    tags: ['Employment', 'Loan', 'MSME', 'Self-Employment', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Shishu: Loans up to Rs.50,000 for new businesses', 'Kishore: Loans Rs.50,001 to Rs.5 lakh for growing businesses', 'Tarun: Loans Rs.5 lakh to Rs.10 lakh for established businesses', 'No collateral required for loans under MUDRA'],
    criteria: ['Must be a non-farm income-generating micro enterprise', 'Proprietorship, partnership, or private limited company', 'Must have a viable business plan', 'Good credit history required for higher loan amounts'],
    steps: ['Approach any public sector bank, MFI, or NBFC', 'Fill MUDRA loan application with business details', 'Submit identity proof, address proof, and business plan', 'Bank evaluates and sanctions appropriate MUDRA category', 'Loan disbursed to business account or via MUDRA card'],
    link: 'https://www.mudra.org.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Self-Employed', 'Unemployed'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Pre-Matric Scholarship for OBC Students',
    description: 'Central government scholarship for OBC students studying in Classes IX and X to prevent dropout and support continuation of education.',
    category: 'education',
    tags: ['Education', 'Scholarship', 'OBC', 'Central'],
    deadline: '2026-10-31',
    benefits: ['Scholarship amount of Rs.4,000 per annum for day scholars', 'Rs.6,000 per annum for hostellers', 'Book grant of Rs.750 per annum', 'Ad-hoc grant for other expenses'],
    criteria: ['Must belong to Other Backward Class (OBC) category', 'Family income must not exceed Rs.1 lakh per annum', 'Must be enrolled in Class IX or Class X', 'Must be studying in a government-recognized school'],
    steps: ['Visit scholarships.gov.in and register as a new user', 'Select Pre-Matric Scholarship for OBC', 'Enter school and personal details', 'Upload OBC certificate, income proof, and previous year marksheet', 'Submit form and note application reference number'],
    link: 'https://scholarships.gov.in/',
    eligibilityRules: { minAge: 13, maxAge: 18, gender: ['Any'], states: ['All'], occupations: ['Student'], incomeRange: ['below_1L'], categories: ['OBC'] },
  },
  {
    title: 'National Fellowship for OBC Students (NF-OBC)',
    description: 'Fellowship for OBC students pursuing M.Phil and Ph.D at recognized universities to provide financial assistance for higher research studies.',
    category: 'education',
    tags: ['Education', 'Scholarship', 'OBC', 'Research', 'Central'],
    deadline: '2026-09-30',
    benefits: ['JRF: Rs.31,000 per month for first two years', 'SRF: Rs.35,000 per month for remaining years', 'Annual contingency grant of Rs.10,000 (JRF) and Rs.20,500 (SRF)', 'HRA as per university norms'],
    criteria: ['Must belong to OBC (non-creamy layer) category', 'Must be registered for M.Phil/Ph.D in a recognized university', 'Should have cleared NET/JRF or equivalent qualifying exam', 'Age: not more than 35 years (relaxable for women and disabled)'],
    steps: ['Apply through the National Fellowship portal on scholarships.gov.in', 'Register and select NF-OBC scheme', 'Fill academic and personal details', 'Upload OBC non-creamy layer certificate, NET/JRF scorecard, and university enrollment proof', 'Submit application and await selection'],
    link: 'https://scholarships.gov.in/',
    eligibilityRules: { minAge: 21, maxAge: 35, gender: ['Any'], states: ['All'], occupations: ['Student'], incomeRange: ['Any'], categories: ['OBC'] },
  },
  {
    title: 'Indira Gandhi National Old Age Pension Scheme (IGNOAPS)',
    description: 'Monthly pension for BPL elderly persons aged 60 years and above to provide social security in old age.',
    category: 'employment',
    tags: ['Pension', 'Senior Citizens', 'BPL', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Rs.200 per month for those aged 60-79 years', 'Rs.500 per month for those aged 80 years and above', 'States typically add their own contribution', 'Direct transfer to bank or post office account'],
    criteria: ['Must be 60 years or above', 'Must belong to Below Poverty Line (BPL) household', 'Must not be receiving pension from any other government scheme', 'Must be Indian citizen'],
    steps: ['Visit Gram Panchayat (rural) or Ward Office (urban)', 'Fill IGNOAPS application form', 'Submit BPL card/ration card, age proof, and bank account details', 'Application verified by Block/District authorities', 'Pension credited monthly to bank/post office account after approval'],
    link: 'https://nsap.nic.in/',
    eligibilityRules: { minAge: 60, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['below_1L'], categories: ['Any'] },
  },
  {
    title: 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
    description: 'National Mission for Financial Inclusion to ensure access to financial services like banking, savings, remittance, credit, insurance, and pension in an affordable manner.',
    category: 'financial_inclusion',
    tags: ['Financial Inclusion', 'Banking', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Zero balance basic savings bank account', 'Rupay Debit card with inbuilt Rs.2 lakh accident insurance cover', 'Overdraft facility up to Rs.10,000 for eligible account holders', 'Direct Benefit Transfer (DBT) directly into the account'],
    criteria: ['Must be an Indian citizen', 'Should not have any other savings bank account', 'Age 10 years and above (for minor accounts)'],
    steps: ['Visit any bank branch or Bank Mitra (Business Correspondent)', 'Fill out the PMJDY account opening form', 'Provide KYC documents (Aadhaar, Voter ID, PAN, etc.)', 'Receive account passbook and RuPay debit card'],
    link: 'https://pmjdy.gov.in/',
    eligibilityRules: { minAge: 10, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Pradhan Mantri Ujjwala Yojana (PMUY)',
    description: 'Social welfare scheme to safeguard the health of women and children by providing them with a clean cooking fuel (LPG) to replace smoky traditional fuels.',
    category: 'social_welfare',
    tags: ['Women', 'Social Welfare', 'Health', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Free LPG connection in the name of the adult woman of the poor household', 'Financial support of Rs.1600 for the connection', 'First refill and hotplate provided free of cost', 'Subsidy of Rs.300 per 14.2 kg cylinder for up to 12 refills/year'],
    criteria: ['Applicant must be a woman above 18 years of age', 'Must belong to a BPL household (SECC 2011 or other defined categories like SC/ST, PMAY-G, etc.)', 'No existing LPG connection in the household'],
    steps: ['Fill the PMUY application form available at LPG distributors or online', 'Submit KYC documents, Aadhaar, and BPL proof', 'Submit bank account details', 'Distributor verifies and issues the connection'],
    link: 'https://www.pmuy.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Female'], states: ['All'], occupations: ['Any'], incomeRange: ['below_1L', '1L_to_2.5L'], categories: ['Any'] },
  },
  {
    title: 'Jal Jeevan Mission (JJM)',
    description: 'Infrastructure initiative to provide safe and adequate drinking water through individual household tap connections by 2024 to all households in rural India.',
    category: 'infrastructure',
    tags: ['Infrastructure', 'Water', 'Rural', 'Health', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Functional Household Tap Connection (FHTC) providing 55 liters per capita per day', 'Safe drinking water leading to better health and reduced water-borne diseases', 'Reduces drudgery for women and girls who walk miles to fetch water'],
    criteria: ['Must be a rural household currently lacking a functional tap connection', 'Community participation required for village water sanitation committees'],
    steps: ['Implemented systematically village by village', 'Gram Panchayat or Village Water and Sanitation Committee handles planning', 'Households register their requirement during the village planning phase', 'Connection installed by the implementing agency'],
    link: 'https://jaljeevanmission.gov.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Stand-Up India Scheme',
    description: 'Empowerment and financial inclusion scheme to facilitate bank loans between Rs.10 lakh and Rs.1 Crore to at least one SC/ST borrower and one woman borrower per bank branch.',
    category: 'social_welfare',
    tags: ['Social Welfare', 'Women', 'SC/ST', 'Business', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Bank loans from Rs.10 lakh to Rs.1 Crore for setting up a new enterprise (greenfield)', 'Composite loan covering term loan and working capital', 'Interest rate lowest applicable rate of the bank', 'Margin money requirement reduced to 15%'],
    criteria: ['Must be an SC/ST or woman entrepreneur, above 18 years of age', 'Enterprise must be in manufacturing, services, agri-allied, or trading sector', 'In case of non-individual enterprises, 51% shareholding must be held by SC/ST or woman', 'Should not be in default to any bank'],
    steps: ['Access the Stand-Up India portal', 'Register and answer brief questions to assess readiness', 'Apply directly at a bank branch or through the portal/Lead District Manager', 'Get application reviewed and loan sanctioned'],
    link: 'https://www.standupmitra.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Female', 'Any'], states: ['All'], occupations: ['Self-Employed', 'Unemployed'], incomeRange: ['Any'], categories: ['SC', 'ST', 'General'] },
  },
  {
    title: 'Soil Health Card Scheme',
    description: 'Agricultural welfare scheme to assist state governments to issue Soil Health Cards to all farmers in the country to provide information on nutrient status of their soil.',
    category: 'agriculture',
    tags: ['Agriculture', 'Farmer Welfare', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Printed report card given to farmers showing soil nutrient status', 'Recommendations on appropriate dosage of nutrients/fertilizers', 'Improves crop yield by promoting balanced fertilizer use', 'Reduces cost of cultivation'],
    criteria: ['Must be a farmer owning agricultural land in India', 'Applicable across all states and districts'],
    steps: ['Soil samples collected by the State Agriculture Department experts', 'Samples tested in soil testing laboratories', 'Soil Health Card generated based on the test results', 'Card is distributed to the farmer via the local agriculture office or online portal'],
    link: 'https://soilhealth.dac.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Digital India Programme',
    description: 'Flagship programme to transform India into a digitally empowered society and knowledge economy, encompassing broadband highways, universal mobile access, and e-governance.',
    category: 'infrastructure',
    tags: ['Infrastructure', 'Digital Initiatives', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Access to high-speed internet through BharatNet in rural areas', 'Digital locker (DigiLocker) for storing and sharing documents securely', 'e-Hospital, e-Sign, and various online government services (UMANG app)', 'Digital literacy training for rural households (PMGDISHA)'],
    criteria: ['Available to all citizens of India', 'Specific sub-schemes like PMGDISHA target one person per eligible rural household'],
    steps: ['Download apps like DigiLocker or UMANG from app stores', 'Register using Aadhaar and mobile number', 'For internet access, connect to local CSCs or public Wi-Fi hotspots provided under the initiative'],
    link: 'https://www.digitalindia.gov.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Deen Dayal Antyodaya Yojana (DAY-NRLM)',
    description: 'Aims to reduce poverty by enabling poor households to access gainful self-employment and skilled wage employment opportunities.',
    category: 'social_welfare',
    tags: ['Social Welfare', 'Rural', 'Women', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Formation of Women Self Help Groups (SHGs)', 'Revolving Fund and Community Investment Support Fund', 'Access to bank credit at subsidized interest rates'],
    criteria: ['Must belong to a poor rural household', 'At least one woman member to be brought under SHG network'],
    steps: ['Contact local Gram Panchayat', 'Join or form a Women SHG', 'Apply for community investment funds through SHG'],
    link: 'https://aajeevika.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Female'], states: ['All'], occupations: ['Unemployed', 'Self-Employed', 'Homemaker'], incomeRange: ['below_1L'], categories: ['Any'] },
  },
  {
    title: 'Rashtriya Vayoshri Yojana (RVY)',
    description: 'Scheme for providing Physical Aids and Assisted-living Devices for Senior citizens belonging to BPL category.',
    category: 'social_welfare',
    tags: ['Social Welfare', 'Senior Citizens', 'BPL', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Free walking sticks, elbow crutches, walkers, hearing aids, wheelchairs, and artificial dentures'],
    criteria: ['Must be a Senior Citizen (60 years and above)', 'Must belong to BPL category or have monthly income below Rs. 15,000', 'Must suffer from age-related disability/infirmity'],
    steps: ['Identify needs through assessment camps organized by ALIMCO', 'Submit BPL proof, Aadhaar, and medical certificate', 'Receive devices at distribution camps'],
    link: 'https://socialjustice.gov.in/',
    eligibilityRules: { minAge: 60, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['below_1L', '1L_to_2.5L'], categories: ['Any'] },
  },
  {
    title: 'Sugamya Bharat Abhiyan (Accessible India Campaign)',
    description: 'Nationwide campaign for achieving universal accessibility for Persons with Disabilities (PwDs).',
    category: 'social_welfare',
    tags: ['Social Welfare', 'Disability', 'Infrastructure', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Enhances accessibility in built environment, transport system, and Information & Communication ecosystem for PwDs'],
    criteria: ['Primarily targets public infrastructure improvements, benefits all Persons with Disabilities'],
    steps: ['Citizens can use the Sugamya Bharat App to report accessibility issues in public buildings and transport'],
    link: 'http://accessibleindia.gov.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'National Family Benefit Scheme (NFBS)',
    description: 'Provides a lump sum financial assistance to BPL households on the death of the primary breadwinner.',
    category: 'social_welfare',
    tags: ['Social Welfare', 'Financial Assistance', 'BPL', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Lump sum assistance of Rs. 20,000 to the bereaved household'],
    criteria: ['The deceased breadwinner must have been between 18 and 59 years of age', 'The family must belong to the BPL category'],
    steps: ['Apply to the local municipal or panchayat office within a stipulated time after the death', 'Submit death certificate and BPL proof'],
    link: 'https://nsap.nic.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['below_1L'], categories: ['Any'] },
  },
  {
    title: 'PM-DAKSH Yojana',
    description: 'National Action Plan for Skilling of Marginalized Persons covering SCs, OBCs, EBCs, DNTs, Safai Karamcharis.',
    category: 'social_welfare',
    tags: ['Social Welfare', 'Skill Development', 'Marginalized', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Free skill training (Up-skilling, Short Term, Long Term, Entrepreneurship)', 'Stipend of Rs. 1,000 to 1,500 per month during training', 'Wage compensation during up-skilling'],
    criteria: ['Must belong to SC, OBC, EBC, DNT, or be a Safai Karamchari', 'Age between 18 to 45 years', 'Income limits apply for OBC/EBC categories'],
    steps: ['Register on the PM-DAKSH portal or app', 'Select the desired training program and nearest institute', 'Complete training and certification'],
    link: 'https://pmdaksh.dosje.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: 45, gender: ['Any'], states: ['All'], occupations: ['Unemployed', 'Student', 'Self-Employed'], incomeRange: ['below_1L', '1L_to_2.5L'], categories: ['SC', 'OBC'] },
  },
  {
    title: 'SMILE (Support for Marginalized Individuals)',
    description: 'Comprehensive welfare scheme for the rehabilitation of transgender persons and persons engaged in begging.',
    category: 'social_welfare',
    tags: ['Social Welfare', 'Marginalized', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Scholarships, skill development, medical care, and shelter homes (Garima Greh) for transgender persons', 'Rehabilitation and education for persons engaged in begging'],
    criteria: ['Transgender persons possessing a valid certificate of identity', 'Individuals rescued from begging'],
    steps: ['Apply for Transgender Identity Certificate via national portal', 'Access services through recognized NGOs and Garima Grehs'],
    link: 'https://socialjustice.gov.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Unemployed'], incomeRange: ['below_1L'], categories: ['Any'] },
  },
  {
    title: 'PM CARES for Children Scheme',
    description: 'Support for children who have lost both parents or surviving parent or legal guardian/adoptive parents due to COVID-19 pandemic.',
    category: 'social_welfare',
    tags: ['Social Welfare', 'Children', 'COVID-19', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Free education and school uniforms', 'Health insurance of Rs. 5 Lakh under PM-JAY', 'Monthly stipend from age 18 to 23', 'Lump sum of Rs. 10 Lakh on reaching 23 years of age'],
    criteria: ['Children who lost parents to COVID-19 between 11.03.2020 and 28.02.2022', 'Child must be under 18 years at the time of parents death'],
    steps: ['Registration and validation done by District Magistrate on the PM CARES portal', 'Benefits disbursed directly to child account'],
    link: 'https://pmcaresforchildren.in/',
    eligibilityRules: { minAge: null, maxAge: 23, gender: ['Any'], states: ['All'], occupations: ['Student', 'Unemployed'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Swadhar Greh Scheme',
    description: 'Aims to provide temporary accommodation, maintenance, and rehabilitative services to women and girls rendered homeless due to family discord, crime, or violence.',
    category: 'social_welfare',
    tags: ['Social Welfare', 'Women', 'Rehabilitation', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Shelter, food, clothing, medical treatment, counseling, and legal aid', 'Vocational training for economic rehabilitation'],
    criteria: ['Women facing domestic violence, family discord, victims of trafficking, or natural disasters', 'Above 18 years of age (children can accompany mothers)'],
    steps: ['Contact local Swadhar Greh operated by NGOs/State Govt', 'Or reach out via Women Helpline (181)'],
    link: 'https://wcd.nic.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Female'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Naya Savera - Free Coaching and Allied Scheme',
    description: 'Free coaching for students belonging to minority communities to prepare for competitive examinations and professional courses.',
    category: 'social_welfare',
    tags: ['Social Welfare', 'Education', 'Minority', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Free coaching fees for competitive exams (UPSC, State PSC, Bank, Medical, Engineering)', 'Stipend of Rs. 2500 for local and Rs. 5000 for outstation students'],
    criteria: ['Must belong to recognized minority communities (Muslim, Christian, Sikh, Buddhist, Jain, Parsi)', 'Family income should not exceed Rs. 6.00 lakh per annum'],
    steps: ['Apply directly to the empanelled coaching institutions', 'Submit income certificate and minority declaration'],
    link: 'https://minorityaffairs.gov.in/',
    eligibilityRules: { minAge: 16, maxAge: 35, gender: ['Any'], states: ['All'], occupations: ['Student', 'Unemployed'], incomeRange: ['below_1L', '1L_to_2.5L', '2.5L_to_5L'], categories: ['Any'] },
  },
  {
    title: 'Garib Kalyan Rojgar Abhiyaan',
    description: 'Employment generation scheme for migrant workers who returned to their home villages during the COVID-19 pandemic.',
    category: 'social_welfare',
    tags: ['Social Welfare', 'Employment', 'Rural', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Immediate employment opportunities in rural public works (e.g., jal jeevan, gram sadak)', 'Development of public infrastructure in villages'],
    criteria: ['Targeted at migrant workers and rural citizens in selected districts across 6 states'],
    steps: ['Engage through local Gram Panchayat for public works taking place under the Abhiyaan'],
    link: 'https://rural.nic.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['Bihar', 'Uttar Pradesh', 'Madhya Pradesh', 'Rajasthan', 'Jharkhand', 'Odisha'], occupations: ['Unemployed', 'Farmer'], incomeRange: ['below_1L', '1L_to_2.5L'], categories: ['Any'] },
  },
  {
    title: 'Paramparagat Krishi Vikas Yojana (PKVY)',
    description: 'Promotes organic farming through the adoption of organic village by cluster approach and PGS certification.',
    category: 'agriculture',
    tags: ['Agriculture', 'Organic Farming', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Financial assistance of Rs. 50,000 per hectare for 3 years', 'Covers organic inputs, certification, labeling, and marketing', 'Helps farmers get better market prices for organic produce'],
    criteria: ['Farmers must form a cluster of 20 hectares', 'Willingness to transition to organic farming methods'],
    steps: ['Form a farmer group/cluster in your village', 'Register with the State Agriculture Department', 'Follow organic protocols and get PGS certification'],
    link: 'https://pgsindia-ncof.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Pradhan Mantri Krishi Sinchayee Yojana (PMKSY)',
    description: 'Aims to enhance physical access of water on farm and expand cultivable area under assured irrigation (Har Khet ko Pani).',
    category: 'agriculture',
    tags: ['Agriculture', 'Irrigation', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Subsidies for setting up micro-irrigation systems (drip and sprinkler)', 'Water conservation and groundwater recharge infrastructure', 'Improves water use efficiency (Per Drop More Crop)'],
    criteria: ['All farmers are eligible, with higher subsidies for small/marginal farmers and SC/ST categories'],
    steps: ['Apply through State Agriculture/Horticulture Department portal', 'Submit land records and quotations for irrigation equipment', 'Installation verified by officials before subsidy release'],
    link: 'https://pmksy.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'e-NAM (National Agriculture Market)',
    description: 'Pan-India electronic trading portal which networks the existing APMC mandis to create a unified national market for agricultural commodities.',
    category: 'agriculture',
    tags: ['Agriculture', 'Market', 'Digital', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Better price discovery for farmers through transparent auction process', 'Access to nationwide buyers rather than just local traders', 'Direct online payment into farmer bank accounts'],
    criteria: ['Must be a farmer or FPO wishing to sell agricultural produce', 'Produce must meet quality parameters'],
    steps: ['Register on the e-NAM portal or mobile app', 'Bring produce to the nearest integrated e-NAM mandi', 'Produce is assayed and put up for online bidding'],
    link: 'https://enam.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'PM Annadata Aay SanraksHan Abhiyan (PM-AASHA)',
    description: 'Umbrella scheme to ensure Minimum Support Price (MSP) to farmers for their produce.',
    category: 'agriculture',
    tags: ['Agriculture', 'MSP', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Price Support Scheme (PSS) for pulses and oilseeds', 'Price Deficiency Payment Scheme (PDPS) compensates farmers if market price falls below MSP', 'Procurement by private agencies on pilot basis'],
    criteria: ['Farmers growing specified crops (pulses, oilseeds, copra) in states implementing the scheme', 'Must be registered on state procurement portals'],
    steps: ['Register on the respective state procurement portal before the harvest season', 'Bring produce to designated procurement centers during the designated period'],
    link: 'https://agricoop.nic.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Rashtriya Krishi Vikas Yojana (RKVY)',
    description: 'Provides states flexibility and autonomy in planning and executing agriculture and allied sector schemes to maximize returns to farmers.',
    category: 'agriculture',
    tags: ['Agriculture', 'Infrastructure', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Funding for pre and post-harvest infrastructure (godowns, cold storage, custom hiring centers)', 'Support for agri-entrepreneurs and startups (RKVY-RAFTAAR)'],
    criteria: ['Farmers, FPOs, and agri-entrepreneurs can apply for sub-schemes under their state RKVY plan'],
    steps: ['Check the State Agriculture Department website for open RKVY projects', 'Submit proposals for infrastructure or agribusiness incubators'],
    link: 'https://rkvy.nic.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer', 'Self-Employed'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Agriculture Infrastructure Fund (AIF)',
    description: 'Medium-long term debt financing facility for investment in viable projects for post-harvest management infrastructure and community farming assets.',
    category: 'agriculture',
    tags: ['Agriculture', 'Infrastructure', 'Loan', 'Central'],
    deadline: 'Ongoing',
    benefits: ['3% interest subvention on loans up to Rs. 2 Crore for 7 years', 'Credit guarantee coverage under CGTMSE for loans up to Rs. 2 Crore', 'Helps build warehouses, cold storages, sorting/grading units'],
    criteria: ['Farmers, FPOs, PACS, Agri-entrepreneurs, and Startups'],
    steps: ['Register on the AIF portal', 'Submit a Detailed Project Report (DPR)', 'Apply for a loan through participating commercial banks or cooperative banks'],
    link: 'https://agriinfra.dac.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer', 'Self-Employed'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Mission for Integrated Development of Horticulture (MIDH)',
    description: 'Centrally Sponsored Scheme for the holistic growth of the horticulture sector covering fruits, vegetables, root & tuber crops, mushrooms, spices, flowers, aromatic plants, coconut, cashew, cocoa and bamboo.',
    category: 'agriculture',
    tags: ['Agriculture', 'Horticulture', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Financial assistance for planting material, greenhouse construction (protected cultivation), and post-harvest management', 'Assistance for setting up cold storages and pack houses'],
    criteria: ['Farmers undertaking horticulture activities', 'Priority given to women and SC/ST farmers'],
    steps: ['Apply through the State Horticulture Department or National Horticulture Board (NHB)', 'Submit project proposal and land documents'],
    link: 'https://midh.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Pradhan Mantri Matsya Sampada Yojana (PMMSY)',
    description: 'Flagship scheme for focused and sustainable development of the fisheries sector in India.',
    category: 'agriculture',
    tags: ['Agriculture', 'Fisheries', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Financial assistance for buying fishing boats, nets, establishing fish ponds, biofloc units, and cold chains', 'Insurance cover for fishers', 'Livelihood support during the fishing ban period'],
    criteria: ['Fishers, fish farmers, fish workers, and fish vendors', 'Self Help Groups and FPOs in fisheries sector'],
    steps: ['Submit application to the District Fisheries Officer', 'Projects are approved by the District Level Committee', 'Subsidy is released post-verification of work'],
    link: 'https://pmmsy.dof.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer', 'Self-Employed'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'National Livestock Mission (NLM)',
    description: 'Ensures quantitative and qualitative improvement in livestock production systems and capacity building of all stakeholders.',
    category: 'agriculture',
    tags: ['Agriculture', 'Livestock', 'Central'],
    deadline: 'Ongoing',
    benefits: ['50% capital subsidy (up to Rs. 50 Lakh) for establishing poultry, sheep, goat, and piggery breeding farms', 'Subsidies for fodder production equipment and chaff cutters'],
    criteria: ['Individuals, FPOs, SHGs, and Section 8 companies involved in animal husbandry'],
    steps: ['Apply through the NLM online portal (nlm.udyamimitra.in)', 'Submit project report and bank consent letter', 'Approval by State Implementing Agency'],
    link: 'https://nlm.udyamimitra.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer', 'Self-Employed'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Sub-Mission on Agricultural Mechanization (SMAM)',
    description: 'Aims to increase the reach of farm mechanization to small and marginal farmers and to regions where availability of farm power is low.',
    category: 'agriculture',
    tags: ['Agriculture', 'Mechanization', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Subsidies (up to 50-80%) on purchase of agricultural machinery like tractors, tillers, and harvesters', 'Financial assistance for setting up Custom Hiring Centers (CHCs)'],
    criteria: ['All farmers are eligible, with higher subsidies for women, SC/ST, and small/marginal farmers'],
    steps: ['Register on the Direct Benefit Transfer in Agriculture Mechanization portal (agrimachinery.nic.in)', 'Select the implement and the dealer', 'Subsidy is credited after physical verification'],
    link: 'https://agrimachinery.nic.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Farmer'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Pradhan Mantri Gram Sadak Yojana (PMGSY)',
    description: 'Nationwide plan to provide good all-weather road connectivity to unconnected villages.',
    category: 'infrastructure',
    tags: ['Infrastructure', 'Rural', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Construction of all-weather roads connecting rural habitations to markets, schools, and hospitals', 'Boosts rural economy and access to basic services'],
    criteria: ['Targets unconnected habitations of designated population size (500+ in plains, 250+ in hilly/desert areas)'],
    steps: ['Roads are planned and executed by the State Rural Roads Development Agencies', 'Citizens can use the "Meri Sadak" app to provide feedback or report complaints'],
    link: 'http://omms.nic.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Smart Cities Mission',
    description: 'Urban renewal and retrofitting program by the Government of India with the mission to develop 100 smart cities across the country.',
    category: 'infrastructure',
    tags: ['Infrastructure', 'Urban', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Improved core infrastructure: adequate water, assured electricity, sanitation, solid waste management', 'Efficient urban mobility, affordable housing, IT connectivity, and e-Governance'],
    criteria: ['Citizens of the 100 selected smart cities benefit from the upgraded infrastructure and services'],
    steps: ['Implemented by Special Purpose Vehicles (SPVs) set up at city level', 'Citizens participate through consultation portals and smart city apps'],
    link: 'https://smartcities.gov.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'AMRUT (Atal Mission for Rejuvenation and Urban Transformation)',
    description: 'Ensures that every household has access to a tap with assured supply of water and a sewerage connection in 500 selected cities.',
    category: 'infrastructure',
    tags: ['Infrastructure', 'Urban', 'Water', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Universal coverage of water supply and sewerage network', 'Development of green spaces and parks', 'Promotion of non-motorized urban transport'],
    criteria: ['Residents of the 500 mission cities'],
    steps: ['Projects executed by Urban Local Bodies (ULBs)', 'Citizens can request water/sewer connections through their respective municipal corporations'],
    link: 'http://amrut.gov.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Bharatmala Pariyojana',
    description: 'A new umbrella program for the highways sector that focuses on optimizing efficiency of freight and passenger movement across the country.',
    category: 'infrastructure',
    tags: ['Infrastructure', 'Highways', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Development of Economic Corridors, Inter Corridors, and Feeder Routes', 'Improvement of border and international connectivity roads', 'Reduces logistics cost and travel time'],
    criteria: ['National level infrastructure project benefiting all citizens and businesses'],
    steps: ['Executed by NHAI, NHIDCL, and State PWDs', 'Land acquisition handled with compensation as per RFCTLARR Act'],
    link: 'https://morth.nic.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'UDAN (Ude Desh ka Aam Naagrik)',
    description: 'Regional Airport Development and Regional Connectivity Scheme aimed at making air travel affordable and widespread.',
    category: 'infrastructure',
    tags: ['Infrastructure', 'Aviation', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Revitalization of unserved and underserved airports', 'Airfares capped at affordable rates (e.g., Rs. 2,500 for a 1-hour flight) on UDAN routes', 'Connects Tier-2 and Tier-3 cities'],
    criteria: ['Any citizen can book subsidized tickets on designated UDAN flight routes'],
    steps: ['Book tickets through standard airline portals or travel aggregators on designated regional routes'],
    link: 'https://www.civilaviation.gov.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'PM Gati Shakti',
    description: 'National Master Plan for multi-modal connectivity, bringing 16 Ministries together for integrated planning and coordinated implementation of infrastructure connectivity projects.',
    category: 'infrastructure',
    tags: ['Infrastructure', 'Logistics', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Seamless movement of people, goods, and services', 'Reduces implementation delays and cost overruns in infrastructure projects', 'Boosts economic growth and exports'],
    criteria: ['Macro-level planning initiative benefiting the logistics sector and general economy'],
    steps: ['Uses a GIS-based digital platform for project planning and monitoring across departments'],
    link: 'https://dpiit.gov.in/logistics-division',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'BharatNet Project',
    description: 'World largest rural broadband connectivity program using Optical Fibre to connect all 2.5 lakh Gram Panchayats (GPs) in India.',
    category: 'infrastructure',
    tags: ['Infrastructure', 'Digital Initiatives', 'Rural', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Provides high-speed broadband connectivity to rural areas', 'Enables e-governance, e-health, e-education, and e-commerce in villages', 'Wi-Fi hotspots setup in Gram Panchayats'],
    criteria: ['Rural citizens residing in Gram Panchayats connected under BharatNet'],
    steps: ['Access internet through Common Service Centres (CSCs) or public Wi-Fi access points deployed in villages'],
    link: 'http://bbnl.nic.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'PM-WANI (Prime Minister Wi-Fi Access Network Interface)',
    description: 'Aims to elevate wireless internet connectivity in the country by setting up public Wi-Fi hotspots across the country via public data offices.',
    category: 'infrastructure',
    tags: ['Infrastructure', 'Digital Initiatives', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Affordable broadband access for the public', 'Opportunity for small shopkeepers (PDOs) to earn extra income by providing Wi-Fi', 'No license fee for providing broadband services'],
    criteria: ['Any citizen can use the Wi-Fi; any shopkeeper/entity can become a Public Data Office (PDO)'],
    steps: ['Download a PM-WANI compliant app', 'Authenticate using e-KYC', 'Connect to any PM-WANI hotspot and purchase data sachets'],
    link: 'https://pmwani.cdot.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Swachh Bharat Mission (Gramin & Urban)',
    description: 'A nationwide campaign to eliminate open defecation and improve solid management.',
    category: 'infrastructure',
    tags: ['Infrastructure', 'Sanitation', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Financial incentive of Rs. 12,000 for construction of Individual Household Latrines (IHHL)', 'Construction of community sanitary complexes', 'Improved public health and hygiene'],
    criteria: ['BPL households and identified APL households (SC/ST, physically handicapped, women-headed, etc.) lacking a toilet'],
    steps: ['Apply through the SBM portal or submit a physical application to the Gram Panchayat/Urban Local Body', 'Subsidy is released post-construction and geo-tagging'],
    link: 'https://swachhbharatmission.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['below_1L', '1L_to_2.5L'], categories: ['Any'] },
  },
  {
    title: 'Sukanya Samriddhi Yojana (SSY)',
    description: 'A government-backed savings scheme targeted at the parents of girl children, offering high interest rates and tax benefits to build a fund for her future education and marriage.',
    category: 'financial_inclusion',
    tags: ['Financial Inclusion', 'Women', 'Girl Child', 'Central'],
    deadline: 'Ongoing',
    benefits: ['High interest rate (currently 8.2% p.a. compounded annually)', 'Tax deduction under Section 80C up to Rs. 1.5 Lakh', 'Interest earned and maturity amount are completely tax-free (EEE status)'],
    criteria: ['Parent or legal guardian of a girl child', 'Girl child must be below 10 years of age', 'Maximum two accounts per family (one for each girl child)'],
    steps: ['Visit any post office or authorized commercial bank', 'Submit SSY account opening form, girl child birth certificate, and parent KYC documents', 'Minimum deposit of Rs. 250 per year required'],
    link: 'https://www.indiapost.gov.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Female'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Sovereign Gold Bond Scheme (SGB)',
    description: 'Government securities denominated in grams of gold, offering an alternative to holding physical gold, paying a fixed interest rate.',
    category: 'financial_inclusion',
    tags: ['Financial Inclusion', 'Investment', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Fixed interest of 2.50% per annum paid semi-annually on the nominal value', 'Capital gains tax exemption on redemption upon maturity (8 years)', 'Eliminates risks and costs of storage associated with physical gold'],
    criteria: ['Resident Indians, HUFs, Trusts, Universities, and Charitable Institutions', 'Minimum investment of 1 gram of gold'],
    steps: ['Apply during the designated subscription periods announced by RBI', 'Purchase through banks, post offices, Stock Holding Corporation, or stock exchanges (NSE/BSE)', 'Discount of Rs. 50 per gram for online payment'],
    link: 'https://rbi.org.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Pradhan Mantri Vaya Vandana Yojana (PMVVY)',
    description: 'A pension scheme announced by the Government of India exclusively for the senior citizens aged 60 years and above, providing assured return.',
    category: 'financial_inclusion',
    tags: ['Financial Inclusion', 'Senior Citizens', 'Pension', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Assured return of 7.40% p.a. payable monthly for 10 years', 'Pension payable monthly, quarterly, half-yearly, or yearly', 'Death benefit: Purchase price returned to nominee'],
    criteria: ['Must be a Senior Citizen (60 years and above)', 'Maximum investment limit is Rs. 15 Lakh per senior citizen'],
    steps: ['Purchase the policy through Life Insurance Corporation (LIC) of India, either offline or online', 'Submit age proof, Aadhaar, and bank details for ECS transfer of pension'],
    link: 'https://licindia.in/',
    eligibilityRules: { minAge: 60, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Senior Citizen Savings Scheme (SCSS)',
    description: 'A government-sponsored savings instrument for individuals aged 60 years or above, offering a regular income stream with the highest safety and tax benefits.',
    category: 'financial_inclusion',
    tags: ['Financial Inclusion', 'Senior Citizens', 'Investment', 'Central'],
    deadline: 'Ongoing',
    benefits: ['High interest rate of 8.2% p.a. paid quarterly', 'Tax deduction under Section 80C', 'Maximum deposit limit increased to Rs. 30 Lakh', 'Safe investment backed by Government of India'],
    criteria: ['Individuals aged 60 years or above', 'Retired civilian employees above 55 years and below 60 years, subject to conditions', 'Retired defense personnel above 50 years'],
    steps: ['Open an SCSS account at any post office or authorized bank', 'Submit age proof, retirement proof (if applicable), and KYC documents'],
    link: 'https://www.indiapost.gov.in/',
    eligibilityRules: { minAge: 60, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Public Provident Fund (PPF)',
    description: 'A popular long-term savings scheme backed by the Government of India, offering safety, attractive interest rates, and fully tax-free returns.',
    category: 'financial_inclusion',
    tags: ['Financial Inclusion', 'Investment', 'Tax Benefit', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Interest rate of 7.1% p.a. compounded annually', 'EEE tax status: Deposits (up to 1.5L), interest, and maturity amount are entirely tax-free', 'Lock-in period of 15 years, extendable in blocks of 5 years', 'Loan facility available from 3rd to 6th financial year'],
    criteria: ['Any resident Indian citizen can open a PPF account', 'Only one account per individual is allowed', 'Minimum deposit of Rs. 500 per year required'],
    steps: ['Open a PPF account at a post office, nationalized bank, or major private banks', 'Submit PPF account opening form with KYC documents', 'Can be easily operated online via net banking'],
    link: 'https://www.indiapost.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'National Savings Certificate (NSC)',
    description: 'A fixed-income investment scheme that you can open with any post office, designed to encourage small to mid-income investors to invest while saving on income tax.',
    category: 'financial_inclusion',
    tags: ['Financial Inclusion', 'Investment', 'Tax Benefit', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Interest rate of 7.7% p.a. compounded annually, paid at maturity', 'Tax deduction under Section 80C up to Rs. 1.5 Lakh', 'Interest earned annually is deemed reinvested and qualifies for 80C deduction', 'Maturity period of 5 years'],
    criteria: ['Any resident Indian citizen can purchase NSCs', 'No maximum limit on investment (minimum Rs. 1000)'],
    steps: ['Visit any post office', 'Fill the NSC application form and submit KYC documents', 'Pay via cash, cheque, or electronic transfer', 'Certificate is issued electronically or in passbook form'],
    link: 'https://www.indiapost.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Kisan Vikas Patra (KVP)',
    description: 'A small savings certificate scheme offered by India Post that doubles a one-time investment in a specific period.',
    category: 'financial_inclusion',
    tags: ['Financial Inclusion', 'Investment', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Investment doubles in 115 months (9 years & 7 months) at current 7.5% interest rate', 'Guaranteed returns backed by the Government of India', 'Can be used as collateral for loans'],
    criteria: ['Any adult resident Indian citizen', 'Can be purchased jointly (up to 3 adults) or on behalf of a minor', 'No maximum investment limit (minimum Rs. 1000)'],
    steps: ['Visit the nearest post office or designated bank branch', 'Submit KVP application form along with identity and address proof', 'Make the deposit and receive the KVP certificate'],
    link: 'https://www.indiapost.gov.in/',
    eligibilityRules: { minAge: 18, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Mahila Samman Savings Certificate (MSSC)',
    description: 'A one-time small savings scheme specifically for women and girls, launched in Budget 2023 to promote financial independence.',
    category: 'financial_inclusion',
    tags: ['Financial Inclusion', 'Women', 'Investment', 'Central'],
    deadline: '2025-03-31',
    benefits: ['Fixed interest rate of 7.5% p.a. compounded quarterly', 'Maximum investment limit of Rs. 2 Lakh for a 2-year tenure', 'Partial withdrawal facility up to 40% allowed after 1 year'],
    criteria: ['Any woman or girl child in India', 'Accounts can be opened individually or by a guardian on behalf of a minor girl'],
    steps: ['Visit any post office or eligible scheduled bank', 'Fill the Account Opening Form (Form-I) with KYC documents', 'Deposit the investment amount (minimum Rs. 1000)'],
    link: 'https://www.indiapost.gov.in/',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Female'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'Post Office Monthly Income Scheme (POMIS)',
    description: 'A low-risk savings scheme that offers a fixed monthly income on a lump sum investment, suitable for retirees and conservative investors.',
    category: 'financial_inclusion',
    tags: ['Financial Inclusion', 'Investment', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Interest rate of 7.4% p.a. paid out monthly', 'Maximum investment limit increased to Rs. 9 Lakh for single accounts and Rs. 15 Lakh for joint accounts', 'Maturity period of 5 years'],
    criteria: ['Any resident Indian citizen', 'Can be opened singly or jointly (up to 3 adults)', 'Minors above 10 years can open an account in their name'],
    steps: ['Open a savings account at the post office if not already holding one', 'Submit POMIS application form with KYC details', 'Make the lump sum deposit via cheque or cash', 'Monthly interest gets auto-credited to the savings account'],
    link: 'https://www.indiapost.gov.in/',
    eligibilityRules: { minAge: 10, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
  {
    title: 'e-RUPI',
    description: 'A cashless and contactless instrument for digital payment. It is a QR code or SMS string-based e-Voucher delivered to the mobile of beneficiaries.',
    category: 'financial_inclusion',
    tags: ['Financial Inclusion', 'Digital Initiatives', 'Central'],
    deadline: 'Ongoing',
    benefits: ['Ensures leak-proof delivery of welfare services', 'Beneficiaries do not need a bank account, internet connection, or smartphone (SMS works on basic phones)', 'Vouchers are purpose-specific (e.g., healthcare, education, fertilizers)'],
    criteria: ['Targeted beneficiaries of specific government schemes or corporate CSR initiatives', 'Valid mobile number required to receive the voucher'],
    steps: ['Government or corporate sponsor identifies beneficiaries and issues the e-voucher via banks', 'Beneficiary receives a QR code or SMS string on their phone', 'Beneficiary shows it at the service provider (e.g., hospital, fertilizer shop) to avail the service cashless'],
    link: 'https://www.npci.org.in/what-we-do/e-rupi/product-overview',
    eligibilityRules: { minAge: null, maxAge: null, gender: ['Any'], states: ['All'], occupations: ['Any'], incomeRange: ['Any'], categories: ['Any'] },
  },
];

async function seedDatabase() {
  try {
    await mongoose.connect(
      process.env.MONGODB_URI || 'mongodb://localhost:27017/grabyojana',
    );
    console.log('Connected to MongoDB');
    await Scheme.deleteMany({});
    console.log('Cleared existing schemes');
    const inserted = await Scheme.insertMany(schemes);
    console.log(`Successfully seeded ${inserted.length} schemes!`);
    const summary = {};
    schemes.forEach((s) => {
      summary[s.category] = (summary[s.category] || 0) + 1;
    });
    console.log('Schemes by category:', summary);
    await mongoose.disconnect();
    console.log('Seeding complete!');
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  }
}

seedDatabase();
